// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODOLIST.DBContext;

#nullable disable

namespace TODOLIST.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20240418002520_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TODOLIST.Data.Entities.ToDo", b =>
                {
                    b.Property<int>("ToDoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToDoId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDo");

                    b.HasData(
                        new
                        {
                            ToDoId = 1,
                            Description = "Es la descripcion",
                            State = true,
                            Title = "Controlers"
                        },
                        new
                        {
                            ToDoId = 2,
                            Description = "Es la descripcion",
                            State = true,
                            Title = "Controlers2"
                        },
                        new
                        {
                            ToDoId = 3,
                            Description = "Es la descripcion",
                            State = true,
                            Title = "Controlers3"
                        });
                });

            modelBuilder.Entity("TODOLIST.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Membrives 8911",
                            Email = "ramirodicarlo2@gmail.com",
                            State = true,
                            UserName = "rdic"
                        });
                });

            modelBuilder.Entity("TODOLIST.Data.Entities.ToDo", b =>
                {
                    b.HasOne("TODOLIST.Data.Entities.User", null)
                        .WithMany("ToDo")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TODOLIST.Data.Entities.User", b =>
                {
                    b.Navigation("ToDo");
                });
#pragma warning restore 612, 618
        }
    }
}
